package com.warehouse.ware.entity;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDate;

@Document(collection = "batches")
public class Batch {
  @Id
  private String id; // Generated by MongoDB [cite: 424]

  private String productSku; // From the first scan [cite: 507]
  private Double weightKg; // Entered by worker [cite: 392, 508]
  private LocalDate expiryDate; // Calculated by SQLite logic
  private String locationCode; // From the second scan (parking spot) [cite: 508]
  private String status = "AVAILABLE"; // Default status [cite: 508]

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getProductSku() {
    return productSku;
  }

  public void setProductSku(String productSku) {
    this.productSku = productSku;
  }

  public Double getWeightKg() {
    return weightKg;
  }

  public void setWeightKg(Double weightKg) {
    this.weightKg = weightKg;
  }

  public LocalDate getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(LocalDate expiryDate) {
    this.expiryDate = expiryDate;
  }

  public String getLocationCode() {
    return locationCode;
  }

  public void setLocationCode(String locationCode) {
    this.locationCode = locationCode;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Batch batchBuilder(String sku, double weight, String locationCode, LocalDate expiryDate,
      String status) {
    Batch batch = new Batch();
    batch.setProductSku(sku);
    batch.setWeightKg(weight);
    batch.setLocationCode(locationCode);
    batch.setExpiryDate(expiryDate);
    batch.setStatus(status);
    return batch;
  }
}
